### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by DorotheaM** [jupyter/jupyter_core#187] opened 2020-04-17 12:59 UTC
Hello, not sure if this is the right platform to address this issue. However, I am on a windows 10 64-bit system. I was using python 3.8.0 32-bit but recently I downloaded anaconda in order to work with jupyter notebooks. When I open the anaconda prompt and type python it show this: 
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Now when I try to create a notebook I have the options: Python 3 and Python 3.8.0. Whichever I choose I get this when I click the Kernel error:

Traceback (most recent call last):
  File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 301, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
    self.write_connection_file()
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\dorot\anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: %1 is not a valid Win32 application

**Comment by jainprasuk1996** [comment] 2020-05-23 19:14
I am facing the same issue too.

**Comment by dhirschfeld** [comment] 2020-05-24 03:30
I'd try a force reinstall for `pywin32` (in the environment where it's being loaded):
```
conda install --force-reinstall pywin32
```

**Comment by SamuelLawrence876** [comment] 2020-07-03 22:10
Also having the problem. has anyone found a fix?

**Comment by ichisa** [comment] 2020-08-14 10:08
Same issue here

**Comment by kunalagg04** [comment] 2020-08-31 18:16
Exact same issue here as well.

**Comment by kunalagg04** [comment] 2020-08-31 18:16
Exact same issue here as well.

**Comment by pseudopunit** [comment] 2020-09-01 18:30
https://stackoverflow.com/questions/61478443/importerror-dll-load-failed-1-is-not-a-valid-win32-application-kernel-error
This resolves the issue for the live state. I don't know the exact solution but you may try out this workaround.
pip install -- pywin32==227

**Comment by MSeal** [comment] 2020-09-01 20:39
Likely this is, or is related to, https://github.com/conda-forge/pywin32-feedstock/issues/18 for conda. The dependency build issue is a little outside jupyter's control plane so I'd look at checking with the pywin32 folks / issues or comment on the existing issues to escalate the issue some.

**Comment by shaktijaiswal** [comment] 2020-09-13 06:44
facing same problem

**Comment by dhirschfeld** [comment] 2020-09-13 10:17
The problem in the original issue is mixing and matching pythons - jupyter is running from anaconda:
```
File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
```
...but it's running the notebook in the original Python environment:
```
File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook
```

So, I'd say just don't do that - there's no reason to install another python alongside `anaconda`.

The solution is to uninstall the other Python version and remove all traces of it (from e.g. the `PATH` env variable)

**Comment by logical-programmers** [comment] 2020-09-22 05:54
> Hello, not sure if this is the right platform to address this issue. However, I am on a windows 10 64-bit system. I was using python 3.8.0 32-bit but recently I downloaded anaconda in order to work with jupyter notebooks. When I open the anaconda prompt and type python it show this:
> Python 3.7.6 (default, Jan 8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
> 
> Now when I try to create a notebook I have the options: Python 3 and Python 3.8.0. Whichever I choose I get this when I click the Kernel error:
> 
> Traceback (most recent call last):
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
> result = await result
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
> yielded = self.gen.throw(*exc_info) # type: ignore
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\handlers.py", line 72, in post
> type=mtype))
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
> value = future.result()
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
> yielded = self.gen.throw(*exc_info) # type: ignore
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
> kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
> value = future.result()
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
> yielded = self.gen.throw(*exc_info) # type: ignore
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
> self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
> value = future.result()
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
> yielded = next(result)
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
> super(MappingKernelManager, self).start_kernel(**kwargs)
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
> km.start_kernel(**kwargs)
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 301, in start_kernel
> kernel_cmd, kw = self.pre_start_kernel(**kw)
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
> self.write_connection_file()
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
> kernel_name=self.kernel_name
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
> with secure_write(fname) as f:
> File "C:\Users\dorot\anaconda3\lib\contextlib.py", line 112, in **enter**
> return next(self.gen)
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_core\paths.py", line 435, in secure_write
> win32_restrict_file_to_user(fname)
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
> import win32api
> ImportError: DLL load failed: %1 is not a valid Win32 application

use this command then your kernel will be running: pip install -- pywin32==227

**Comment by Sandsten** [comment] 2020-09-28 11:20
I was plagued by the same issue with `ImportError: DLL load failed: %1 is not a valid Win32 application`
This happened when i tried to open vscode through anaconda-navigator and run a jupyter notebook. It then complained about missing packages for running the kernel through a vscode popup, i pressed install, it installed something and then everything broke down. 

Then I managed to get it to work by reinstalling anaconda as admin (through right clicking the installer) and then installing it in it's default path `C:\ProgramData\Anaconda3`. I reinstalled it a bunch of times prior to this with no avail, both without admin and with admin directly under `C:\`. No idea if installing it in it's default path as admin did the trick or something entirely different.

**Comment by ikki99** [comment] 2020-10-07 12:25
I'm not using anaconda but i have the same problem, i tried the pip install -- pywin32==227 but did not work.

**Comment by Shai2008** [comment] 2020-10-12 09:02
Can someone help? I am facing the same issue

**Comment by carlodri** [comment] 2020-10-12 19:54
From the  paths in the OP's traceback it seems like he/she has some coexisting installations of Python on the system, maybe leftovers from previous installations, or he/she is mixing `conda`and `pip`, which should be avoided whenever possible. Could this be the source of the issue?

**Comment by sachin-v-s** [comment] 2020-10-19 18:28
This worked for me

pip install -- pywin32==227

**Comment by MertTanyur** [comment] 2020-10-26 12:19
> https://stackoverflow.com/questions/61478443/importerror-dll-load-failed-1-is-not-a-valid-win32-application-kernel-error
> This resolves the issue for the live state. I don't know the exact solution but you may try out this workaround.
> pip install -- pywin32==227

Not only my current problem solved also It repaired my jupyter notebook in vs code  kernel error

**Comment by posve** [comment] 2020-11-04 20:43
> The problem in the original issue is mixing and matching pythons - jupyter is running from anaconda:
> 
> ```
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
> ```
> 
> ...but it's running the notebook in the original Python environment:
> 
> ```
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook
> ```
> 
> So, I'd say just don't do that - there's no reason to install another python alongside `anaconda`.
> 
> The solution is to uninstall the other Python version and remove all traces of it (from e.g. the `PATH` env variable)

This worked for me. The issue was exactly the same as the original poster, and I saw that there were several installations of Python being referenced. So I deleted the previous traces of Python, and the notebook immediately worked.

**Comment by kevin-bates** [comment] 2020-11-04 21:42
Got a positive trend going here!  Thank you for the updates - closing.

**Closed by kevin-bates** 2020-11-04 21:42 UTC

**Comment by harshdhamecha** [comment] 2020-12-02 08:36
> 
> 
> The problem in the original issue is mixing and matching pythons - jupyter is running from anaconda:
> 
> ```
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
> ```
> 
> ...but it's running the notebook in the original Python environment:
> 
> ```
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook
> ```
> 
> So, I'd say just don't do that - there's no reason to install another python alongside `anaconda`.
> 
> The solution is to uninstall the other Python version and remove all traces of it (from e.g. the `PATH` env variable)

This really helps! Thanks a lot!

**Comment by Azmisov** [comment] 2020-12-04 21:40
First start python from your console and see if you can import win32api. For me, it will look like:
```
> conda activate my_env
> python
Python 3.5.5 |Anaconda, Inc.| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

Then at least you know whether its a problem with your conda environment or jupyter.

**Comment by tuansoibk** [comment] 2020-12-25 09:19
I had even more problem after uninstalling pywin32 package and was not able to install it again. I have to reinstall Python 3.9 afterward. IMHO, a better approach for pywin32 package is:
````pip install --upgrade pywin32
The kernel just worked as expected afterward :)

**Comment by valen7zhi** [comment] 2021-01-06 22:58
> I had even more problems after uninstalling pywin32 package and was not able to install it again. I have to reinstall Python 3.9 afterward. IMHO, a better approach for pywin32 package is:
> `pip install --upgrade pywin32`
> The kernel just worked as expected eventually :)

It worked for me. ✌

**Comment by Prince6112** [comment] 2021-01-25 06:39
> This worked for me
> 
> pip install -- pywin32==227

Same! It worked for me to. Thanks

**Comment by baduk1** [comment] 2021-02-13 21:59
> https://stackoverflow.com/questions/61478443/importerror-dll-load-failed-1-is-not-a-valid-win32-application-kernel-error
> This resolves the issue for the live state. I don't know the exact solution but you may try out this workaround.
> pip install -- pywin32==227

Worked for me! Thank you!

**Comment by slowtoaccept** [comment] 2021-02-15 15:27
Finally!!! This worked for me. See below for warnings and incompatibilities. Very frustrating, even with the latest Anacononda. Thanks to all with your suggestions. I also added path C:\Users\Jerry\Anaconda3\Lib\site-packages\pywin32_system32 prior to upgrade.

(base) C:\Users\Jerry>pip install --upgrade pywin32
Collecting pywin32
  Downloading pywin32-300-cp38-cp38-win_amd64.whl (9.3 MB)
     |████████████████████████████████| 9.3 MB 6.8 MB/s
Installing collected packages: pywin32
  Attempting uninstall: pywin32
    Found existing installation: pywin32 227
    Uninstalling pywin32-227:
      Successfully uninstalled pywin32-227
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

nbclient 0.5.1 requires jupyter-client>=6.1.5, but you'll have jupyter-client 6.1.2 which is incompatible.
**Successfully installed pywin32-300**

**Comment by Azmisov** [comment] 2021-03-11 03:52
So mine ended up being a strange case where it only occurred if the kernel's conda environment was 3.5.*. If I made a python 3.6+ conda environment, I didn't get any pywin32 DLL errors. I tried all the commands in this thread, and they seemed like they _should_ work, but nothing did. I think for me the problem is occurring because my system already has a default installation of python 3.5, outside any conda environment; my guess is the pywin32 DLL's are not getting looked up correctly, due to that system installation of python 3.5 already present. Unfortunately, this computer is a work computer and I don't have permission to try uninstalling the system python to see if that resolves the problem.

In any case, using a python 3.6+ conda environment worked for me. So see if you can uninstall your system python or select a different python version than what your system provides.

**Comment by BoldizsarZopcsak** [comment] 2021-03-17 09:44
I had the wrong version of tornado installed (6.0.4) but you need 6.1 to work with notebook. This worked for me:
`pip uninstall tornado`
`pip install tornado`
in your base of Anaconda.

**Comment by TedLeem** [comment] 2021-03-23 07:11
> > I had even more problems after uninstalling pywin32 package and was not able to install it again. I have to reinstall Python 3.9 afterward. IMHO, a better approach for pywin32 package is:
> > `pip install --upgrade pywin32`
> > The kernel just worked as expected eventually :)
> 
> It worked for me. ✌

this works for me too thank you!!!!!!!!!!

**Comment by mtachaudhary** [comment] 2021-05-24 09:10
Solution
[https://github.com/jupyter/notebook/issues/4980#issuecomment-846892941](url)

**Comment by meeseeksmachine** [comment] 2021-06-06 00:30
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyter-notebook-cells-dont-run/9472/4

**Comment by mudit573** [comment] 2021-06-06 17:08
for anaconda  use this : 
https://stackoverflow.com/questions/46335789/anaconda-navigator-wont-launch-windows-10

if get an error like: DLL load failed while importing _win32sysloader: %1 is not a valid Win32 applicatiodone
open anaconda prompt and run: pip install -- pywin32==227

**Comment by mridullpandey** [comment] 2021-07-10 14:07
This worked for me

pip install -- pywin32==227

**Comment by 0sergio-hash** [comment] 2021-09-12 19:58
> I had even more problems after uninstalling pywin32 package and was not able to install it again. I have to reinstall Python 3.9 afterward. IMHO, a better approach for pywin32 package is:
> `pip install --upgrade pywin32`
> The kernel just worked as expected eventually :)

This worked for me! 
I have a couple environments and it was only giving me this error on one of them. The files all looked exactly the same as far as I could tell, and I don't know how many different times I uninstalled/reinstalled or downgraded/upgraded pywin32, but when I tried this it worked ! lol.

**Comment by renzhonglu11** [comment] 2021-09-21 20:09
> The problem in the original issue is mixing and matching pythons - jupyter is running from anaconda:
> 
> ```
> File "C:\Users\dorot\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
> ```
> 
> ...but it's running the notebook in the original Python environment:
> 
> ```
> File "C:\Users\dorot\AppData\Roaming\Python\Python37\site-packages\notebook
> ```
> 
> So, I'd say just don't do that - there's no reason to install another python alongside `anaconda`.
> 
> The solution is to uninstall the other Python version and remove all traces of it (from e.g. the `PATH` env variable)

this one works for me, thanks

**Comment by dustinpeng** [comment] 2022-04-01 03:42
> I'd try a force reinstall for `pywin32` (in the environment where it's being loaded):
> 
> ```
> conda install --force-reinstall pywin32
> ```

this command worked for me.
my environment has pywin32-302 installed after command issued.
previouslly is pywin32-303 when I has the problem.

**Comment by shivkavitha** [comment] 2024-03-13 13:34
Hi,
I have the same issue as "Original error was: DLL load failed while importing _multiarray_umath: %1 is not a valid Win32 application" and neither 'pip install pywin32' nor 'pip install --upgrade pywin32' helped. 

Besides, I am using only pip and no conda. Any help is appreciated!

Many Thanks!
